development:
  stripe_secret_key: 'sk_test_51MR9ieSH5vA36rA5IbcYtoJM3GMadVO58nx7NdNzF3I5KHoeqDNXK7dwtH9l5WozAToXpNXXsptSCKUj9ejNyaiz00mLMZ55po'
  stripe_publishable_key: 'pk_test_51MR9ieSH5vA36rA5SMwQxHqho2BPOxRu66elAvPjyb7PzhbmZwBmGRr22Bg4vgpBzX8N0hlMq7q6bFRISHTE2KpX001VSjt4gy'
